const { REACT_APP_ADMIN_API_HOST, REACT_APP_ADMIN_API_PATH } = process.env

module.exports = {
  ENDPOINTS: {
    CAMP_INVITATIONS: `${REACT_APP_ADMIN_API_HOST}${REACT_APP_ADMIN_API_PATH}/camps/invitations`,
    CAMPS: `${REACT_APP_ADMIN_API_HOST}${REACT_APP_ADMIN_API_PATH}/camps/`,
    CAMPS_AND_CAMPAIGNS: `${REACT_APP_ADMIN_API_HOST}${REACT_APP_ADMIN_API_PATH}/camps/with_details`,
    USERS:  `${REACT_APP_ADMIN_API_HOST}${REACT_APP_ADMIN_API_PATH}/users/`
  },

  CAMP_STATUS: {
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    CLOSED: 'CLOSED',
    CAMPTREE: 'CAMPTREE'
  },
  CAMP_INVITATION_STATUS: {
    INVITED: 'INVITED',
    COMPLETE: 'COMPLETE',
  },
  CAMPAIGN_TYPES: {
    REGISTRATION: 'REGISTRATION',
    COUNSELOR: 'COUNSELOR',
    CUSTOM: 'CUSTOM',
  },
  CAMPAIGN_STATUS: {
    INCOMPLETE: 'INCOMPLETE',
    ACTIVE: 'ACTIVE',
    CLOSED: 'CLOSED',
    ARCHIVED: 'ARCHIVED',
  },
  REFERRAL_TYPE: {
    REFERRAL: 'REFERRAL',
    INQUIRY: 'INQUIRY',
    REGISTRATION: 'REGISTRATION',
  },
  BASE_URL: `${REACT_APP_ADMIN_API_HOST}${REACT_APP_ADMIN_API_PATH}`
}
